# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 580)
        MainWindow.setMinimumSize(QtCore.QSize(980, 580))
        MainWindow.setMaximumSize(QtCore.QSize(980, 580))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_products_save = QtWidgets.QToolButton(self.centralwidget)
        self.btn_products_save.setGeometry(QtCore.QRect(550, 301, 160, 100))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(12)
        self.btn_products_save.setFont(font)
        self.btn_products_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sales_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_products_save.setIcon(icon)
        self.btn_products_save.setIconSize(QtCore.QSize(64, 64))
        self.btn_products_save.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_products_save.setObjectName("btn_products_save")
        self.btn_products_delete = QtWidgets.QToolButton(self.centralwidget)
        self.btn_products_delete.setGeometry(QtCore.QRect(220, 131, 160, 100))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_products_delete.setFont(font)
        self.btn_products_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_products_delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_products_delete.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/products_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_products_delete.setIcon(icon1)
        self.btn_products_delete.setIconSize(QtCore.QSize(64, 64))
        self.btn_products_delete.setShortcut("")
        self.btn_products_delete.setCheckable(False)
        self.btn_products_delete.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_products_delete.setObjectName("btn_products_delete")
        self.hline1 = QtWidgets.QFrame(self.centralwidget)
        self.hline1.setGeometry(QtCore.QRect(0, 450, 991, 20))
        self.hline1.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline1.setObjectName("hline1")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 1, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.btn_products_back = QtWidgets.QToolButton(self.centralwidget)
        self.btn_products_back.setGeometry(QtCore.QRect(550, 131, 160, 100))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(12)
        self.btn_products_back.setFont(font)
        self.btn_products_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/categories_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_products_back.setIcon(icon2)
        self.btn_products_back.setIconSize(QtCore.QSize(64, 64))
        self.btn_products_back.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_products_back.setArrowType(QtCore.Qt.NoArrow)
        self.btn_products_back.setObjectName("btn_products_back")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 1, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_products_new = QtWidgets.QToolButton(self.centralwidget)
        self.btn_products_new.setGeometry(QtCore.QRect(220, 301, 160, 100))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_products_new.setFont(font)
        self.btn_products_new.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_products_new.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_products_new.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/revenues_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_products_new.setIcon(icon3)
        self.btn_products_new.setIconSize(QtCore.QSize(64, 64))
        self.btn_products_new.setCheckable(False)
        self.btn_products_new.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_products_new.setObjectName("btn_products_new")
        self.lbl_products = QtWidgets.QLabel(self.centralwidget)
        self.lbl_products.setGeometry(QtCore.QRect(330, 21, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_products.setFont(font)
        self.lbl_products.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_products.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_products.setWordWrap(True)
        self.lbl_products.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_products.setObjectName("lbl_products")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 1, 0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.hline1_2 = QtWidgets.QFrame(self.centralwidget)
        self.hline1_2.setGeometry(QtCore.QRect(0, 69, 991, 20))
        self.hline1_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline1_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline1_2.setObjectName("hline1_2")
        self.vline1 = QtWidgets.QFrame(self.centralwidget)
        self.vline1.setGeometry(QtCore.QRect(760, 79, 20, 381))
        self.vline1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline1.setObjectName("vline1")
        self.vline1_3 = QtWidgets.QFrame(self.centralwidget)
        self.vline1_3.setGeometry(QtCore.QRect(170, 80, 20, 380))
        self.vline1_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline1_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline1_3.setObjectName("vline1_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_products_save.setToolTip(_translate("MainWindow", "Salvar"))
        self.btn_products_save.setAccessibleName(_translate("MainWindow", "btn_products_save"))
        self.btn_products_save.setText(_translate("MainWindow", "Vendas"))
        self.btn_products_save.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.btn_products_delete.setToolTip(_translate("MainWindow", "Deletar"))
        self.btn_products_delete.setAccessibleName(_translate("MainWindow", "btn_products_delete"))
        self.btn_products_delete.setText(_translate("MainWindow", " Produtos"))
        self.hline1.setAccessibleName(_translate("MainWindow", "hline1"))
        self.btn_products_back.setToolTip(_translate("MainWindow", "Voltar"))
        self.btn_products_back.setAccessibleName(_translate("MainWindow", "btn_products_back"))
        self.btn_products_back.setText(_translate("MainWindow", "Categorias"))
        self.btn_products_back.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.btn_products_new.setToolTip(_translate("MainWindow", "Novo"))
        self.btn_products_new.setAccessibleName(_translate("MainWindow", "btn_products_new"))
        self.btn_products_new.setText(_translate("MainWindow", "Faturamento"))
        self.btn_products_new.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.lbl_products.setToolTip(_translate("MainWindow", "Lista de Produtos"))
        self.lbl_products.setAccessibleName(_translate("MainWindow", "lbl_products"))
        self.lbl_products.setText(_translate("MainWindow", "Mercado do João"))
        self.hline1_2.setAccessibleName(_translate("MainWindow", "hline1"))
        self.vline1.setAccessibleName(_translate("MainWindow", "vline1"))
        self.vline1_3.setAccessibleName(_translate("MainWindow", "vline1"))
import resources_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
